-- modules/combat/battle_state.lua
local State = {}

State.visible = false
State.attacker = nil
State.defender = nil
State.platformImage = nil
State.platformX = 0
State.platformY = 0
State.battleTimer = 0
State.runDuration = 0.8
State.attackDuration = 0.7
State.returnDuration = 0.8
State.battleDuration = State.runDuration + State.attackDuration + State.returnDuration
State.transitionPhase = "none"
State.transitionTimer = 0
State.transitionCloseDuration = 0.4
State.transitionWhiteDuration = 0.08
State.transitionMoveDuration = 0.4
State.transitionCenterX = 0
State.transitionCenterY = 0
State.transitionTargetW = 0
State.transitionTargetH = 0
State.transitionSquareSize = 0
State.transitionStartAttackerX = 0
State.transitionStartAttackerY = 0
State.transitionStartDefenderX = 0
State.transitionStartDefenderY = 0

State.hitEffectImage = nil
State.hitEffectActive = false
State.hitEffectStartTime = 0
State.hitEffectDuration = 0.6
State.breakAnimDuration = 0.7
State.hitFrameStartTime = 0
State.defenderHitX = 0
State.defenderHitY = 0
State.overlayShakeActive = false
State.overlayShakeStartTime = 0
State.overlayShakeDuration = 0.3
State.overlayShakeIntensity = 35
State.hitTargetX = 0
State.hitTargetY = 0
State.missEffectImage = nil
State.missEffectPlayerImage = nil
State.missEffectEnemyImage = nil
State.missEffectActive = false
State.missEffectStartTime = 0
State.missFrameStartTime = 0
State.missAnimDuration = 1.2
State.attackFrameIndex = 0
State.attackSwingPlayed = false
State.attackHitPlayed = false
State.currentAttackIsCritical = false
State.isLastAttackHit = true
State.playerAttackPreview = { hit = 0, damage = 0, crit = 0 }
State.enemyAttackPreview = { hit = 0, damage = 0, crit = 0 }
State.defenderHealthDisplay = 0
State.playerHealthDisplay = 0
State.defenderPreviousHealth = 0
State.playerPreviousHealth = 0
State.healthAnimDuration = 0.8
State.healthAnimStartTime = 0
State.isHealthAnimating = false
State.damageApplied = false
State.damageAmount = 0
State.healthAnimDurationActual = 0.8
State.battlePhase = "initial_attack"
State.counterattackEnabled = true
State.counterattackDamage = 0
State.counterattackApplied = false
State.defenderCounterAttackPlayed = false
State.calculatedAttackDamage = 0  -- Pre-calculated damage for current attack
State.currentAttackHit = false    -- Pre-calculated hit result for current attack
State.attackResultCalculated = false  -- Flag to prevent recalculation
State.projectileActive = false
State.projectileStartTime = 0
State.projectileSpawned = false
State.projectileFrame4Time = 0
State.projectileSpawnDelay = 0.15
State.projectileStartX = 0
State.projectileStartY = 0
State.projectileTargetX = 0
State.projectileTargetY = 0
State.projectileDuration = 0.25  -- Time for projectile to travel
State.projectileImage = nil

function State.resetTimers()
    State.battleTimer = 0
    State.hitEffectActive = false
    State.hitFrameStartTime = 0
    State.attackFrameIndex = 0
    State.attackSwingPlayed = false
    State.attackHitPlayed = false
    State.isLastAttackHit = true
    State.defenderCounterAttackPlayed = false
    State.transitionPhase = "none"
    State.transitionTimer = 0
    State.isHealthAnimating = false
    State.healthAnimStartTime = 0
    State.damageApplied = false
    State.damageAmount = 0
    State.healthAnimDurationActual = 0.8
    State.battlePhase = "initial_attack"
    State.counterattackEnabled = true
    State.counterattackDamage = 0
    State.counterattackApplied = false
    State.calculatedAttackDamage = 0
    State.currentAttackHit = false
    State.attackResultCalculated = false
    State.missEffectActive = false
    State.missFrameStartTime = 0
    State.projectileActive = false
    State.projectileStartTime = 0
    State.projectileSpawned = false
    State.projectileFrame4Time = 0
    State.overlayShakeActive = false
    State.overlayShakeStartTime = 0
end

return State
